version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: realestate-postgres
    restart: always
    environment:
      POSTGRES_DB: realestate_db
      POSTGRES_USER: realestate_user
      POSTGRES_PASSWORD: realestate_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: